version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/code
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
        keys:
          - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew build
      - save_cache:
        paths: 
         - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
        path: build/libs
        destination: libs
